### ISSUE TITLE
map server setup

### ISSUE THREAD

**Issue by donghyunyoo** [hulop/MapService#10]
I am trying to setup a new map server, but your document is not clear and old. 
can you make a more detail document for newbies like me?

**Comment by dsato80** [comment]
Could you describe what is your exact pain point? In other words, what did you do, what happened, and what is not clear to resolve it?

**Comment by donghyunyoo** [comment]
These are what I did.

1. install Eclipse IDE for Java EE Developers
2. git clone source code
3. import MapService and SampleMap in Eclipse
4. export WAR file
5. excute "cf push your_app_name -p war_file_name" 
--> cf: command not found

Questions...
1. What should I do for the prerequisites?
2. In SETUP.md, 
"Define IBM Bluemix Server. Then push MapService app to Bluemix"
How can I define the server? 
How can I push the MapService app? does it mean upload?
I can't follow "Deploy MapService Server" section because

**Comment by dsato80** [comment]
Thank you @donghyunyoo !
@itohtaka , could you support his setup? and update the document if possible

**Comment by itohtaka** [comment]
- updated MapService/SETUP.md file
  - removed CLI usages
  - added tutorial links
- switched to Maven java project
- please use download-lib.sh for JS libraries

Best regards

**Comment by itohtaka** [comment]
> I can't find IBM Eclipse Tools for IBM Cloud in Eclipse marketplace.

Have you tried "Find" function? 
I am using Eclipse Oxygen. Not  tried on other version.

![image](https://user-images.githubusercontent.com/15723477/43350911-63743a44-9246-11e8-9b47-bc4af2dfaf09.png)


How about install step 3
https://developer.ibm.com/wasdev/downloads/#asset/tools-IBM_Eclipse_Tools_for_IBM_Cloud
> 3. Drag and drop the Install button below onto the Eclipse toolbar, then follow the prompts.

**Comment by donghyunyoo** [comment]
I am using Photon. 
I tried "Find" in market place and "drag and drop the install button". 
I couldn't fint it and drag & drop doen't work.

**Comment by itohtaka** [comment]
Seems Photon is not supported yet. 

Please use Oxygen for now.
http://www.eclipse.org/downloads/packages/release/oxygen/3a/eclipse-jee-oxygen-3a

**Comment by itohtaka** [comment]
> Can you please describe the steps in detail?

It is hard to describe. Please watch video.
https://www.youtube.com/watch?v=urupsrAsLow

for more informations
https://www.ibm.com/cloud/eclipse

**Comment by donghyunyoo** [comment]
Thank you for the video. 
I defined a new server and deployed the app. when I opened "https://your_app_name.mybluemix.net/admin.jsp",  I got these errors.  
![screenshot from 2018-08-01 23-36-17](https://user-images.githubusercontent.com/23063017/43561214-07b764be-95e4-11e8-967c-3673f07ef04f.png)
Do you guess what is the reason?

And I can see only cmu-tools app in Kris' IBM Cloud account. Do you know where cmu-map app is?

**Comment by itohtaka** [comment]
Do you have any java compile errors on eclipse markers view?

Also I noticed many JS libraries are missing. 
![image](https://user-images.githubusercontent.com/15723477/43563121-802b25ee-965b-11e8-974d-2a371a5b328a.png)

**Comment by donghyunyoo** [comment]
I have never used java before and I don’t know JS library and how to add JS libraries.
And where are the JS libraries?
That’s why I asked the detail description. 
I don’t know what I have to do with eclipse and IBM cloud and Bluemix.
Where should I  deploy the app? IBM cloud? Bluemix?
For a new site, Do I have to create a new map server? Or can I use cmu map server?

**Comment by dsato80** [comment]
Hi @donghyunyoo 

As @itohtaka mentioned above, please use [download-lib.sh](https://github.com/hulop/MapService/blob/master/download-lib.sh) to download JS libraries.

I understand your situation, but please learn basic things such as Java, Javascript, and Eclipse by yourself. We are happy to support our software. Also, we could not answer any specific project matter here, public issue.

**Comment by donghyunyoo** [comment]
Finally, I built and run MapServer on IBM cloud. Thank you for your help. 
I can access admin console and POI editor. 
However, I can't see floorplans that I registered to cmu-tools in MapServer editor.
I made a new DB for hospital in cmu-tools and uploaded floorplans, and export floormap.json.
Do you have any idea on this problem?

**Comment by dsato80** [comment]
The last problem is not related to this repository directly. So I close this issue.
